### ISSUE TITLE
Chybí ListBox control

### ISSUE THREAD

**Issue by Prochazka2** [ProfiiQus/SmartFP-Configurator#1]
Chybí generování ListBoxControlu, je to velice důležitá komponenta, která by měla být přidána.

Děkuji
Aleš Procházka

**Comment by profiiqus** [comment]
Bude přidáno Davidem. Děkujeme.

**Comment by Prochazka2** [comment]
Chci to do příštího týdne, Děkuji

**Comment by profiiqus** [comment]
Closed as of [5ca5d06](https://github.com/ProfiiQus/SmartFP-Configurator/commit/5ca5d06d6a889433b67c9e6cc8ac8aa5fbcabdfc)
